name: CI Interakcija Clovek Racunalnik

on:
  push:
    branches:
      - main

jobs:
  windows-wpf-job:
    runs-on: windows-latest
    name: Windows Build & Test WPF
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
  
      - name: Run tests
        run: dotnet test WPFNaloga1/WPFNaloga1.sln --configuration Debug --logger "trx;LogFileName=test_results.trx" --results-directory TestResults
  
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows
          path: TestResults
  local-job:
    runs-on: self-hosted
    name: Local Debug Build & Analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build in Debug
        run: dotnet build WPFNaloga1/WPFNaloga1/WPFNaloga1.csproj --configuration Debug

      - name: Static Code Analysis
        continue-on-error: true
        run: dotnet format WPFNaloga1/WPFNaloga1/WPFNaloga1.csproj --verify-no-changes

      - name: Generate build artifacts
        run: |
          mkdir -p artifacts
          cp -r bin/Debug/* artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts-local
          path: artifacts
